"""Strict, read-only release gate. Requires Python 3 + Pillow; no Android checkout.

Run: python tools/validate-active-release.py --http http://127.0.0.1:8765
The reviewed manifest is immutable input, NEVER regenerated by this command.
Text hashes use Git's LF representation; binary hashes use exact response bytes.
The manifest cannot hash itself: pin its SHA in the external predeploy report.
The legacy Node suite (including its historical assertions) remains separate.
"""
import argparse
import csv
import hashlib
import io
import json
from html.parser import HTMLParser
from pathlib import Path
import re
import subprocess
from urllib.parse import unquote, urljoin, urlparse
from urllib.request import urlopen
from PIL import Image

SITE = Path(__file__).resolve().parents[1]
MANIFEST = 'tools/active-release-manifest.json'
HOST = 'https://balkanconverter.com'
VOID = set('area base br col embed hr img input link meta param source track wbr'.split())
CHECKS = 0


def require(ok, message):
    global CHECKS
    CHECKS += 1
    if not ok:
        raise ValueError(message)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def canonical(data, mode):
    return data.replace(b'\r\n', b'\n') if mode == 'git-lf' else data


def git(*args):
    return subprocess.run(['git', '-c', f'safe.directory={SITE.as_posix()}', *args],
                          cwd=SITE, check=True, stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE).stdout


class Page(HTMLParser):
    """This site's explicit-close HTML: strict nesting, unique IDs, references."""
    def __init__(self, source, name):
        super().__init__(convert_charrefs=True)
        self.name, self.stack, self.ids = name, [], set()
        self.images, self.refs, self.links, self.text = [], [], [], []
        self.meta, self.html, self.scripts = {}, {}, []
        self.feed(source)
        self.close()
        require(not self.stack, f'{name}: unclosed tags {self.stack}')

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        require(len(a) == len(attrs), f'{self.name}: duplicate attribute {tag}')
        if tag == 'html': self.html = a
        if 'id' in a:
            require(a['id'] not in self.ids, f'{self.name}: duplicate ID {a["id"]}')
            self.ids.add(a['id'])
        if tag not in VOID: self.stack.append(tag)
        if tag == 'img': self.images.append(a)
        if tag == 'a': self.links.append(a.get('href'))
        if tag == 'meta': self.meta[a.get('name', a.get('property'))] = a.get('content')
        for field in ('src', 'href'):
            if a.get(field): self.refs.append(a[field])
        if a.get('srcset'):
            self.refs.extend(v.strip().split()[0] for v in a['srcset'].split(','))

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in VOID: self.handle_endtag(tag)

    def handle_endtag(self, tag):
        require(tag not in VOID and bool(self.stack) and self.stack[-1] == tag,
                f'{self.name}: mismatched closing {tag}, stack {self.stack}')
        self.stack.pop()

    def handle_data(self, text):
        if 'script' in self.stack: self.scripts.append(text)
        elif 'body' in self.stack and text.strip(): self.text.append(text.strip())


def resolve(ref, page):
    parsed = urlparse(urljoin(HOST + '/' + page, ref))
    if parsed.netloc != 'balkanconverter.com': return None
    path = unquote(parsed.path).lstrip('/')
    if not path or path.endswith('/'): path += 'index.html'
    require('..' not in Path(path).parts, f'outside source: {ref}')
    return path, unquote(parsed.fragment)


def validate(args):
    manifest_bytes = (SITE / MANIFEST).read_bytes()
    manifest = json.loads(manifest_bytes)
    require(manifest['schema'] == 1, 'schema')
    files = manifest['files']
    inventory = set(git('ls-files', '-z').decode().split('\0')) | set(
        git('ls-files', '--others', '--exclude-standard', '-z').decode().split('\0'))
    inventory.discard('')
    require(inventory == set(files) | {MANIFEST},
            f'exact source inventory mismatch: extra={inventory-set(files)-{MANIFEST}}, missing={set(files)-inventory}')
    negative_tests = 0
    for path, expected in files.items():
        content = canonical((SITE / path).read_bytes(), expected['hash_mode'])
        require(bool(content), f'zero-byte file: {path}')
        require(len(content) == expected['size'], f'size mismatch: {path}')
        require(sha(content) == expected['sha256'], f'SHA mismatch: {path}')
        # In-memory mutations: prove every exact checksum rejects altered bytes.
        require(sha(content + b'\0') != expected['sha256'], f'mutation not rejected: {path}')
        negative_tests += 1
    require(inventory | {'UNREVIEWED_FILE'} != set(files) | {MANIFEST}, 'extra-file rejection')
    negative_tests += 1
    base = manifest['baseline_commit']
    changed = set(git('diff', '--name-only', base).decode().splitlines()) | (
        inventory - set(git('ls-tree', '-r', '--name-only', base).decode().splitlines()))
    require(changed == set(manifest['reviewed_changes']), 'unreviewed change set')
    for path in manifest['protected_files']:
        require(canonical((SITE/path).read_bytes(), files[path]['hash_mode']) == git('show', f'{base}:{path}'),
                f'protected baseline changed: {path}')

    image_count = 0
    for path, expected in manifest['visual_assets'].items():
        blob = (SITE/path).read_bytes()
        require(sha(blob) == expected['sha256'], f'canonical visual SHA: {path}')
        require(len(blob) == expected['size'], f'canonical visual size: {path}')
        with Image.open(io.BytesIO(blob)) as image:
            require(list(image.size) == expected['dimensions'], f'canonical visual dimensions: {path}')
            require(image.format.lower() == expected['format'].lower(), f'canonical visual format: {path}')
            image.verify()
        image_count += 1
    require(len(set(v['sha256'] for p,v in manifest['visual_assets'].items() if p != 'assets/app-icon.png')) == image_count-1,
            'unexpected duplicate among versioned visual assets')
    require(manifest['visual_assets']['assets/app-icon.png']['sha256'] ==
            manifest['visual_assets']['assets/icons/v1-5-11/app-icon-v1-5-11.png']['sha256'], 'privacy compatibility icon')

    locales = json.loads((SITE/'site-locales.json').read_text(encoding='utf-8'))['locales']
    require([x['webLocale'] for x in locales] == manifest['locales'], 'locale inventory changed')
    pages, locale_rows, active = {}, [], set()
    for locale in locales:
        home = (locale['url'].lstrip('/') + 'index.html')
        policy = locale['privacyUrl'].lstrip('/')
        for path in [home, policy]:
            pages[path] = Page((SITE/path).read_text(encoding='utf-8'), path)
            active.add(path)
        page = pages[home]
        old = Page(git('show', f'{base}:{home}').decode(), 'baseline:' + home)
        require(page.text == old.text and page.links == old.links, f'visible copy/navigation changed: {home}')
        require(len(page.scripts) == len(old.scripts) == 1, f'inline script count: {home}')
        structured, old_structured = json.loads(page.scripts[0]), json.loads(old.scripts[0])
        require(structured.pop('image') == HOST+'/assets/icons/v1-5-11/app-icon-v1-5-11.png', f'JSON-LD icon: {home}')
        require(old_structured.pop('image') == HOST+'/assets/app-icon.png', f'baseline JSON-LD icon: {home}')
        require(structured == old_structured, f'other JSON-LD fields changed: {home}')
        for key in ('description', 'og:description', 'twitter:description'):
            require(page.meta.get(key) == old.meta.get(key), f'metadata changed: {home}/{key}')
        require(page.html.get('lang') == old.html.get('lang') and page.html.get('dir') == old.html.get('dir'), f'language/direction: {home}')
        shots = [i for i in page.images if '/screenshots/' in i['src']]
        require(len(shots) == 5, f'screenshot count: {home}')
        stems = ['main-converter','main-converter','actual-cost','travel-board','saved-sets']
        for n, (shot, stem) in enumerate(zip(shots, stems)):
            prefix = '/assets/screenshots/v1-5-11/' + stem
            require(shot['src'] == prefix+'-540.webp', f'current screenshot/order: {home}')
            require(shot.get('alt','').strip() and '1.4' not in shot['alt'], f'required current alt: {home}')
            require(shot.get('width') == '1080' and shot.get('height') == '1884', f'screenshot dimensions: {home}')
            expected_srcset = f'{prefix}-540.webp 540w, {prefix}-810.webp 810w, {prefix}.webp 1080w'
            require(shot.get('srcset') == expected_srcset and bool(shot.get('sizes')), f'responsive variants: {home}')
            require(shot.get('loading') == 'lazy' if n else shot.get('loading') != 'lazy' and shot.get('fetchpriority') == 'high', f'image priority: {home}')
        if locale['webLocale'] != 'en':
            old_shots = [i for i in old.images if '/screenshots/' in i['src']]
            require([i['alt'] for i in shots] == [i['alt'] for i in old_shots], f'localized alt regression: {home}')
        for key in ('og:image', 'twitter:image'):
            require(page.meta.get(key) == HOST+'/assets/og-v1-5-11.png', f'current social image: {home}')
            page.refs.append(page.meta[key])
        require(not any('assets/app-icon.png' in r or 'assets/og.png' in r or 'assets/screenshots/' in r and '/v1-5-11/' not in r for r in page.refs), f'stale active home visual: {home}')
        locale_rows.append(dict(locale=locale['webLocale'], page_path=home, hero_image=shots[0]['src'],
            gallery_images=' | '.join(s['src'] for s in shots[1:]), app_icon='/assets/icons/v1-5-11/app-icon-v1-5-11.png',
            og_image=page.meta['og:image'], alt_text_status='PASS; existing translations preserved',
            old_1_4_reference='No', qa_status='STRICT_SOURCE_PASS'))

    for path, page in pages.items():
        for img in page.images:
            require('alt' in img, f'missing alt: {path}')
            require(int(img.get('width',0)) > 0 and int(img.get('height',0)) > 0, f'missing dimensions: {path}')
        for ref in page.refs:
            resolved = resolve(ref,path)
            if resolved:
                target, fragment = resolved
                require(target in inventory and (SITE/target).is_file(), f'broken local reference: {path} -> {ref}')
                if fragment and target in pages:
                    require(fragment in pages[target].ids, f'broken anchor: {path} -> {ref}')
                active.add(target)
    # Collect local module imports/CSS URLs (browser-executed source only).
    for path in list(active):
        if Path(path).suffix in {'.css','.js','.mjs'}:
            source = (SITE/path).read_text(encoding='utf-8')
            refs = re.findall(r'''(?:from\s*|import\s*)['"]([^'"]+)['"]|url\(['"]?([^)'"\s]+)''',source)
            for pair in refs:
                ref = next(v for v in pair if v)
                resolved = resolve(ref,path)
                if resolved:
                    target,_ = resolved
                    require(target in inventory, f'broken runtime reference: {path} -> {target}')
                    active.add(target)
    webmanifest = json.loads((SITE/'site.webmanifest').read_text(encoding='utf-8'))
    for icon in webmanifest['icons']:
        target,_ = resolve(icon['src'], 'site.webmanifest')
        require(target in manifest['visual_assets'], f'manifest icon: {target}')
        require(icon['sizes'] == 'x'.join(map(str,manifest['visual_assets'][target]['dimensions'])), 'manifest icon dimensions')
        active.add(target)
    active.update(manifest['visual_assets'])
    require(sorted(active) == manifest['active_runtime_files'], 'active runtime graph differs from reviewed manifest')
    http = []
    if args.http:
        for path in sorted(active):
            url = args.http.rstrip('/') + '/' + path + args.query
            with urlopen(url, timeout=30) as response:
                body = response.read()
                require(response.status == 200, f'HTTP {path}')
                expected = files[path]
                require(sha(canonical(body,expected['hash_mode'])) == expected['sha256'], f'HTTP content SHA: {path}')
                http.append(dict(path=path,status=response.status,sha256=sha(body),size=len(body)))
    result = dict(status='PASS', checks=CHECKS, source_files=len(inventory), pinned_files=len(files),
                  manifest_sha256=sha(canonical(manifest_bytes,'git-lf')), locales=len(locales),
                  active_html_pages=len(pages), visual_assets=image_count, runtime_files=len(active),
                  protected_files=len(manifest['protected_files']), mutation_checks=negative_tests,
                  broken_links=0,missing_alts=0,missing_assets=0,old_active_visual_references=0,
                  unresolved_active_checksum_mismatches=0,http_checks=http,
                  source_inventory=sorted(inventory),active_runtime_files=sorted(active))
    if args.report:
        out = Path(args.report)
        out.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
        with out.with_suffix('.csv').open('w',encoding='utf-8',newline='') as stream:
            writer=csv.DictWriter(stream,fieldnames=locale_rows[0].keys())
            writer.writeheader(); writer.writerows(locale_rows)
    print(json.dumps({k:v for k,v in result.items() if k not in {'http_checks','source_inventory','active_runtime_files'}},indent=2))
    print(f'HTTP exact-content checks: {len(http)}/{len(http)} PASS')


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--http',help='optional local or deployed public origin')
    parser.add_argument('--query',default='',help='cache-busting query, e.g. ?analytics_qa=1&v=COMMIT')
    parser.add_argument('--report',help='write JSON + locale CSV outside the source worktree')
    validate(parser.parse_args())
